<?php

namespace CodingSunshine\Ensemble\Console;

use CodingSunshine\Ensemble\Schema\SchemaDiagramExporter;
use CodingSunshine\Ensemble\Schema\SchemaWriter;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

class ExportCommand extends Command
{
    protected function configure(): void
    {
        $this
            ->setName('export')
            ->setDescription('Export an ensemble.json schema as markdown, Mermaid ER diagram, or schema-graph JSON')
            ->addArgument('path', InputArgument::OPTIONAL, 'Path to the ensemble.json file', './ensemble.json')
            ->addOption('format', 'f', InputOption::VALUE_REQUIRED, 'Output format: markdown, mermaid, or schema-graph', 'markdown')
            ->addOption('output', 'o', InputOption::VALUE_REQUIRED, 'Write to a file instead of stdout');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $schema = SchemaWriter::read($input->getArgument('path'));
        $format = $input->getOption('format');

        if (! in_array($format, ['markdown', 'mermaid', 'schema-graph'], true)) {
            $output->writeln('<error>Format must be: markdown, mermaid, or schema-graph</error>');

            return Command::FAILURE;
        }

        if ($format === 'mermaid') {
            $content = SchemaDiagramExporter::toMermaid($schema);
        } elseif ($format === 'schema-graph') {
            $content = json_encode(SchemaDiagramExporter::toSchemaGraph($schema), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
        } else {
            $content = $this->buildMarkdown($schema);
        }

        if ($outputPath = $input->getOption('output')) {
            file_put_contents($outputPath, $content);
            $output->writeln('');
            $output->writeln("  <fg=green>Exported to {$outputPath}</>");
            $output->writeln('');

            return Command::SUCCESS;
        }

        $output->write($content);

        return Command::SUCCESS;
    }

    protected function buildMarkdown(array $schema): string
    {
        $lines = [];
        $app = $schema['app'] ?? [];
        $appName = $app['name'] ?? 'Unnamed Application';

        $lines[] = "# {$appName}";
        $lines[] = '';
        $lines[] = 'Generated by [Laravel Ensemble CLI](https://github.com/coding-sunshine/ensemble-cli).';
        $lines[] = '';

        $lines[] = '## Application';
        $lines[] = '';
        $lines[] = '| Property | Value |';
        $lines[] = '|----------|-------|';

        foreach (['name', 'stack', 'ui'] as $key) {
            if (isset($app[$key])) {
                $lines[] = "| {$key} | {$app[$key]} |";
            }
        }

        if (isset($schema['version'])) {
            $lines[] = "| schema version | {$schema['version']} |";
        }

        $lines[] = '';

        $lines = array_merge($lines, $this->buildModelsMarkdown($schema));
        $lines = array_merge($lines, $this->buildControllersMarkdown($schema));
        $lines = array_merge($lines, $this->buildPagesMarkdown($schema));
        $lines = array_merge($lines, $this->buildNotificationsMarkdown($schema));
        $lines = array_merge($lines, $this->buildWorkflowsMarkdown($schema));
        $lines = array_merge($lines, $this->buildRecipesMarkdown($schema));

        return implode("\n", $lines)."\n";
    }

    /**
     * @return array<int, string>
     */
    protected function buildModelsMarkdown(array $schema): array
    {
        $models = $schema['models'] ?? [];

        if (empty($models)) {
            return [];
        }

        $lines = ['## Models', ''];

        foreach ($models as $name => $definition) {
            $traits = [];

            if (! empty($definition['softDeletes'])) {
                $traits[] = 'soft-deletes';
            }

            $traitSuffix = $traits ? ' ('.implode(', ', $traits).')' : '';
            $lines[] = "### {$name}{$traitSuffix}";
            $lines[] = '';

            $fields = $definition['fields'] ?? [];

            if (! empty($fields)) {
                $lines[] = '#### Fields';
                $lines[] = '';
                $lines[] = '| Field | Type |';
                $lines[] = '|-------|------|';

                foreach ($fields as $fieldName => $fieldType) {
                    $lines[] = "| `{$fieldName}` | `{$fieldType}` |";
                }

                $lines[] = '';
            }

            $relationships = $definition['relationships'] ?? [];

            if (! empty($relationships)) {
                $lines[] = '#### Relationships';
                $lines[] = '';
                $lines[] = '| Name | Type |';
                $lines[] = '|------|------|';

                foreach ($relationships as $relName => $relType) {
                    $lines[] = "| `{$relName}` | `{$relType}` |";
                }

                $lines[] = '';
            }

            $policies = $definition['policies'] ?? [];

            if (! empty($policies)) {
                $lines[] = '#### Policies';
                $lines[] = '';

                foreach ($policies as $action => $rule) {
                    $lines[] = "- **{$action}**: {$rule}";
                }

                $lines[] = '';
            }
        }

        return $lines;
    }

    /**
     * @return array<int, string>
     */
    protected function buildControllersMarkdown(array $schema): array
    {
        $controllers = $schema['controllers'] ?? [];

        if (empty($controllers)) {
            return [];
        }

        $lines = ['## Controllers', ''];
        $lines[] = '| Controller | Type |';
        $lines[] = '|------------|------|';

        foreach ($controllers as $name => $definition) {
            $resource = $definition['resource'] ?? 'web';
            $lines[] = "| {$name}Controller | {$resource} |";
        }

        $lines[] = '';

        return $lines;
    }

    /**
     * @return array<int, string>
     */
    protected function buildPagesMarkdown(array $schema): array
    {
        $pages = $schema['pages'] ?? [];

        if (empty($pages)) {
            return [];
        }

        $lines = ['## Pages', ''];
        $lines[] = '| Route | Layout |';
        $lines[] = '|-------|--------|';

        foreach ($pages as $routeName => $definition) {
            $layout = $definition['layout'] ?? 'default';
            $lines[] = "| `{$routeName}` | {$layout} |";
        }

        $lines[] = '';

        return $lines;
    }

    /**
     * @return array<int, string>
     */
    protected function buildNotificationsMarkdown(array $schema): array
    {
        $notifications = $schema['notifications'] ?? [];

        if (empty($notifications)) {
            return [];
        }

        $lines = ['## Notifications', ''];
        $lines[] = '| Notification | Channels | Recipient | Subject |';
        $lines[] = '|--------------|----------|-----------|---------|';

        foreach ($notifications as $name => $definition) {
            $channels = isset($definition['channels']) ? implode(', ', $definition['channels']) : 'mail';
            $to = $definition['to'] ?? '—';
            $subject = $definition['subject'] ?? '—';
            $lines[] = "| {$name} | {$channels} | `{$to}` | {$subject} |";
        }

        $lines[] = '';

        return $lines;
    }

    /**
     * @return array<int, string>
     */
    protected function buildWorkflowsMarkdown(array $schema): array
    {
        $workflows = $schema['workflows'] ?? [];

        if (empty($workflows)) {
            return [];
        }

        $lines = ['## Workflows', ''];

        foreach ($workflows as $name => $definition) {
            $model = $definition['model'] ?? '?';
            $field = $definition['field'] ?? '?';
            $lines[] = "### {$name}";
            $lines[] = '';
            $lines[] = "**Model:** {$model} / **Field:** `{$field}`";
            $lines[] = '';

            if (isset($definition['states'])) {
                $lines[] = '**States:** '.implode(' → ', $definition['states']);
                $lines[] = '';
            }

            if (isset($definition['transitions'])) {
                $lines[] = '| Transition | From | To |';
                $lines[] = '|------------|------|----|';

                foreach ($definition['transitions'] as $transName => $trans) {
                    $from = $trans['from'] ?? '?';
                    $to = $trans['to'] ?? '?';
                    $lines[] = "| {$transName} | {$from} | {$to} |";
                }

                $lines[] = '';
            }
        }

        return $lines;
    }

    /**
     * @return array<int, string>
     */
    protected function buildRecipesMarkdown(array $schema): array
    {
        $recipes = $schema['recipes'] ?? [];

        if (empty($recipes)) {
            return [];
        }

        $lines = ['## Recipes', ''];
        $lines[] = '| Recipe | Package |';
        $lines[] = '|--------|---------|';

        foreach ($recipes as $recipe) {
            $name = $recipe['name'] ?? 'unknown';
            $package = $recipe['package'] ?? '(built-in)';
            $lines[] = "| {$name} | `{$package}` |";
        }

        $lines[] = '';

        return $lines;
    }
}
